name: workflow_02
on: [repository_dispatch]
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Triggering Wokflow 2"
      - name: Checkout
        uses: actions/checkout@v3.5.3
        with:
          name: sebastian-mair/QSA-Hackathon-Fall2023 # repository: # optional, default is ${{ github.repository }}
