name: workflow_02
on: [repository_dispatch]
jobs:
  grade:
    runs-on: ubuntu-latest
    env:
      GITHUB_CONTEXT: ${{ toJson(github.event.client_payload.repository) }}
    steps:
      - name: Pls work
        run: |
          echo ${{ env.GITHUB_CONTEXT }}
      - uses: actions/checkout@v3.5.3
      - uses: actions/checkout@v3.5.3
        with:
          repository: ${{ fromJSON(env.GITHUB_CONTEXT) }}
          path: ./QSA-Hackathon-Fall2023
      - uses: actions/setup-python@v3.1.4
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Run pytest
        run: pytest --junit-xml=test-results.xml
      - name: Surface failing tests
        if: always()
        uses: pmeier/pytest-results-action@main
        with:
          path: test-results.xml
          summary: true
          display-options: fEX
          fail-on-empty: true
