name: workflow_02
on: [repository_dispatch]
jobs:
  grade:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.5.3
      - uses: actions/checkout@v3.5.3
        with:
          repository: sebastian-mair/QSA-Hackathon-Fall2023 # repository: # optional, default is ${{ github.repository }}
      - uses: actions/setup-python@v3.1.4
        with:
          python-version: 3.8
      - name: Test Output
        run: echo "Triggering Grading"
        # TODO: run pytest.
      
